version: "3.8"

services:
  db:
    image: mariadb:10.11  #imagen oficial de MariaDB
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql                 
      - ./sql:/docker-entrypoint-initdb.d:ro  
    networks: [appnet]

  app:
    image: ewancess/php-sample-app:1.0.1  #imagen publicada en Docker Hub
    depends_on: [db]
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: sample
      DB_USER: sampleuser
      DB_PASS: samplepass
    networks: [appnet]

volumes:
  dbdata:

networks:
  appnet:
